### ISSUE TITLE
Polyfill crashes when `WebGLRenderingContext` is undefined

### ISSUE THREAD

**Issue by etimberg** [greggman/oes-vertex-array-object-polyfill#1]
Obviously one shouldn't use this when WebGL is not enabled, but I ran into this in some test code where WebGL was not enabled.

I think a fix is as simple as conditionally running the polyfill at the end of the IIFE.

```javascript
if (WebGLRenderingContext) {
  setupVertexArrayObject();
}
```

**Comment by greggman** [comment]
Good point. Updated

https://github.com/greggman/oes-vertex-array-object-polyfill/commit/40ac085cf438fcdd6b301095ce7aa271593feac8

**Comment by etimberg** [comment]
thanks @greggman
